<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Tasks' => 'Задачи',
  'User details' => 'Детали пользователя',
  'User management' => 'Управление пользователями',
  'User role details' => 'Детали пользовательской роли',
  'User role management' => 'Управление ролями пользователей',
  'User task details' => 'Детали пользовательской задачи',
  'User task management' => 'Управление задачами пользователей',
  'Additional tasks' => 'Дополнительные задачи',
  'Changes has been saved' => 'Изменения сохранены',
  'Choose another code' => 'Выберите другой код',
  'Common controllers' => 'Общие контроллеры',
  'Create' => 'Создать',
  'Creating' => 'Создание',
  'Delete selected' => 'Удалить выбранное',
  'Delete selected elements ?' => 'Удалить выбранные элементы ?',
  'Edit' => 'Редактировать',
  'Editing' => 'Редактирование',
  'Hide all' => 'Свернуть',
  'Manage' => 'К управлению',
  'Modules' => 'Модули',
  'No' => 'Нет',
  'Open all' => 'Развернуть',
  'Refresh controllers list' => 'Обновить список контроллеров',
  'Roles' => 'Роли',
  'Save' => 'Сохранить',
  'Saved' => 'Сохранено',
  'Yes' => 'Да',
);
